name: Check file and Preview DNS changes

on: pull_request

jobs:
  check:
    if: github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: DNSControl check
        uses: wblondel/dnscontrol-action@c47e0e742495410c31ac255276093a46c60f5fe7 # 5.3.0
        with:
          args: check --variable home_ip=${{ secrets.HOME_IP }}

  preview:
    if: github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DESEC_API_TOKEN: ${{ secrets.DESEC_API_TOKEN }}
      DYNADOT_API_KEY: ${{ secrets.DYNADOT_API_KEY }}
      OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
      OVH_APP_SECRET_KEY: ${{ secrets.OVH_APP_SECRET_KEY }}
      OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
      SPACESHIP_API_KEY: ${{ secrets.SPACESHIP_API_KEY }}
      SPACESHIP_API_SECRET: ${{ secrets.SPACESHIP_API_SECRET }}
    needs: check

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: DNSControl preview
        uses: wblondel/dnscontrol-action@c47e0e742495410c31ac255276093a46c60f5fe7 # 5.3.0
        id: dnscontrol_preview
        with:
          args: preview --variable home_ip=${{ secrets.HOME_IP }}
