name: Dependabot Makefile updater
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Get Dependabot PR metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout PR
        if: contains(steps.metadata.outputs.dependency-names, 'wblondel/dnscontrol-action')
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Fetch latest Docker image tag
        if: contains(steps.metadata.outputs.dependency-names, 'wblondel/dnscontrol-action')
        id: get-docker-image-tag
        run: |
          DOCKER_IMAGE="ghcr.io/stackexchange/dnscontrol"
          LATEST_TAG=$(docker pull --quiet $DOCKER_IMAGE | awk -F: '{print $2}')
          echo "::set-output name=tag::$LATEST_TAG"

      - name: Update Makefile
        if: contains(steps.metadata.outputs.dependency-names, 'wblondel/dnscontrol-action')
        id: update-makefile
        run: |
          # Change this so that it replaces the content of the variable DNSCONTROL_DOCKER_IMAGE instead
          echo "${{ steps.get-docker-image-tag.outputs.tag }}" > Makefile

      - name: Commit and push
        if: contains(steps.metadata.outputs.dependency-names, 'wblondel/dnscontrol-action')
        run: |
          git commit -m "Update Makefile"
          git push
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

